services:
  aihumanwarning:
    build: .
    ports:
      - "6666:5000"
    volumes:
      - ./data /app/data
    environment:
        - SECRET_KEY=${SECRET_KEY}
        - JWT_SECRET_KEY=${SECRET_KEY}
        # if you want to use custom database
        # - DATABASE_URL=${DATABASE_URL}