"""add seconds column

Revision ID: 2cf6fdc23dc7
Revises: eb44a8da577c
Create Date: 2026-07-05 21:34:02.751133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf6fdc23dc7'
down_revision = 'eb44a8da577c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_stream_records')
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('sec')

    op.create_table('_alembic_tmp_stream_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stream_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=80), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
