"""add image url column

Revision ID: 678f3eb4e217
Revises: e7550830df9c
Create Date: 2026-07-05 20:37:20.865592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678f3eb4e217'
down_revision = 'e7550830df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_records', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
