"""add enable column

Revision ID: e7550830df9c
Revises: fdc0e295230c
Create Date: 2026-07-05 20:01:24.408541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7550830df9c'
down_revision = 'fdc0e295230c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('enable')

    # ### end Alembic commands ###
