"""add llm info

Revision ID: eb44a8da577c
Revises: 678f3eb4e217
Create Date: 2026-07-05 20:45:09.524331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb44a8da577c'
down_revision = '678f3eb4e217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_records', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_baseurl', sa.String(length=256)))
        batch_op.add_column(sa.Column('llm_apikey', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('llm_modelname', sa.String(length=256)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('llm_modelname')
        batch_op.drop_column('llm_apikey')
        batch_op.drop_column('llm_baseurl')

    with op.batch_alter_table('stream_records', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
